FROM ubuntu:xenial
MAINTAINER Jon Palmer <nextgenusfs@gmail.com>

RUN apt-get update && \
	apt-get install --fix-missing -y build-essential curl file g++ git make ruby2.3 ruby2.3-dev uuid-runtime \
	sudo wget libboost-all-dev libncurses5-dev zlib1g-dev locales debconf-utils && \
	sudo apt-get install -y autoconf autogen python-setuptools  \
	perl-modules-5.22 cpanminus cmake ncbi-blast+ xvfb default-jdk && \
	ln -sf ruby2.3 /usr/bin/ruby && ln -sf gem2.3 /usr/bin/gem && \
    localedef -i en_US -f UTF-8 en_US.UTF-8 && \
	useradd -m -s /bin/bash linuxbrew && \
	echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers && \
    echo "mysql-server mysql-server/root_password password pasa1" | sudo debconf-set-selections && \
    echo "mysql-server mysql-server/root_password_again password pasa1" | sudo debconf-set-selections && \
    sudo apt-get install -y mysql-server libdbd-mysql-perl libdbi-perl && \
    git clone https://github.com/Linuxbrew/brew.git /home/linuxbrew/.linuxbrew && \
    chown -R linuxbrew: /home/linuxbrew/.linuxbrew && \
	cd /home/linuxbrew/.linuxbrew && \
	git remote set-url origin https://github.com/Linuxbrew/brew.git

USER linuxbrew

WORKDIR /home/linuxbrew

ENV PATH=/home/linuxbrew/funannotate:/home/linuxbrew/conda/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/augustus/bin:/home/linuxbrew/.linuxbrew/opt/repeatmasker/libexec/util:/home/linuxbrew/gm_et_linux_64/gmes_petap:/home/linuxbrew/signalp-4.1:/home/linuxbrew/phobius:/home/linuxbrew/Trinity:/home/linuxbrew/RapMap/bin:/home/linuxbrew/mummer/bin:/home/linuxbrew/tRNAscan-SE:/home/linuxbrew/eggnog-mapper:$PATH \
	SHELL=/bin/bash \
    AUGUSTUS_CONFIG_PATH=/home/linuxbrew/augustus/config \
    EVM_HOME=/home/linuxbrew/.linuxbrew/opt/evidencemodeler \
    GENEMARK_PATH=/home/linuxbrew/gm_et_linux_64/gmes_petap \
    BAMTOOLS_PATH=/usr/local/bin \
    PASAHOME=/home/linuxbrew/PASApipeline \
    TRINITYHOME=/home/linuxbrew/Trinity \
    FUNANNOTATE_DB=/home/linuxbrew/DB \
    PERL5LIB=/usr/local/lib/perl5/site_perl

RUN sudo cpanm Getopt::Long Pod::Usage File::Basename threads threads::shared \
    Thread::Queue Carp Data::Dumper YAML Hash::Merge Logger::Simple Parallel::ForkManager \
    DBI Text::Soundex Scalar::Util::Numeric Clone Bio::Perl && \
    brew doctor || true && brew tap homebrew/science && brew tap nextgenusfs/tap && \
    brew update && brew install mummer blast kent-tools repeatscout trf rmblast recon \
    braker evidencemodeler proteinortho repeatmasker repeatmodeler && \
    rm /home/linuxbrew/.linuxbrew/bin/tblastn && brew unlink mysql && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    sudo /bin/bash ~/miniconda.sh -b -p /home/linuxbrew/conda && \
    rm ~/miniconda.sh && sudo chown -R linuxbrew: /home/linuxbrew/conda && \
    conda update -y conda && \
    conda install -y numpy pandas scipy matplotlib seaborn natsort scikit-learn psutil biopython requests && \
    conda install -y -c etetoolkit ete3 ete_toolchain && \
    conda install -y -c bioconda goatools fisher bedtools blat hmmer exonerate diamond tbl2asn \
    raxml trimal mafft kallisto bowtie2 infernal samtools hisat2 && rm /home/linuxbrew/conda/bin/perl && \
    wget https://github.com/pezmaster31/bamtools/archive/v2.5.0.tar.gz && tar -zxvf v2.5.0.tar.gz && \
    rm v2.5.0.tar.gz && mv bamtools-2.5.0 bamtools && cd bamtools && mkdir build && cd build && \
    cmake .. && make && sudo make install && cd /usr/include && \
    sudo ln -f -s ../local/include/bamtools/ && \
    cd /usr/lib/ &&  sudo ln -f -s /usr/local/lib/bamtools/libbamtools.* . && cd $HOME && \
    wget http://bioinf.uni-greifswald.de/augustus/binaries/old/augustus-3.2.3.tar.gz && \
    tar -zxvf augustus-3.2.3.tar.gz && rm augustus-3.2.3.tar.gz && mv augustus-3.2.3 augustus && \
    cd augustus && make clean && make && cd $HOME && \
    ln -s /home/linuxbrew/.linuxbrew/opt/braker/libexec/filterGenemark.pl /home/linux/augustus/scripts/filterGeneMark.pl && \
    wget https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v2.5.1.tar.gz && \
    tar -zxvf Trinity-v2.5.1.tar.gz && rm Trinity-v2.5.1.tar.gz && \
    mv trinityrnaseq-Trinity-v2.5.1 Trinity && cd Trinity && make && make plugins && cd $HOME && \
    wget https://github.com/COMBINE-lab/RapMap/archive/v0.5.0.tar.gz && \
    tar -zxvf v0.5.0.tar.gz && rm v0.5.0.tar.gz && mv RapMap-0.5.0 RapMap && \
    cd RapMap && mkdir build && cd build && cmake .. && make && make install && cd $HOME && \
    wget http://research-pub.gene.com/gmap/src/gmap-gsnap-2017-06-20.tar.gz && \
    tar -zxvf gmap-gsnap-2017-06-20.tar.gz && rm gmap-gsnap-2017-06-20.tar.gz && \
    mv gmap-2017-06-20/ gmap && cd gmap/ && ./configure && make && sudo make install && cd $HOME && \
    wget https://github.com/PASApipeline/PASApipeline/archive/pasa-v2.2.0.tar.gz && \
    tar -zxvf pasa-v2.2.0.tar.gz && rm pasa-v2.2.0.tar.gz && \
    mv PASApipeline-pasa-v2.2.0 PASApipeline && cd PASApipeline && make clean && make && cd $HOME && \
    wget http://faculty.virginia.edu/wrpearson/fasta/fasta36/fasta-36.3.8e.tar.gz && \
    tar -zxvf fasta-36.3.8e.tar.gz && rm fasta-36.3.8e.tar.gz && \
    cd fasta-36.3.8e/src && make -f ../make/Makefile.linux fasta36 && cd $HOME && \
    ln -s /home/linuxbrew/fasta-36.3.8e/bin/fasta36 /home/linuxbrew/.linuxbrew/bin/fasta && \
    wget http://trna.ucsc.edu/software/trnascan-se-2.0.0.tar.gz && \
    tar -zxvf trnascan-se-2.0.0.tar.gz && rm trnascan-se-2.0.0.tar.gz && \
    mv tRNAscan-SE-2.0 tRNAscan-SE && cd tRNAscan-SE && ./configure && make && cd $HOME && \
    mkdir /home/linuxbrew/data

RUN git clone git://github.com/nextgenusfs/funannotate.git && \
    git checkout 92f4458b2cc10eff2f2e7dd70c2444b439b1487c .
       
COPY pasa_conf.txt /home/linuxbrew/PASApipeline/pasa_conf/conf.txt
