[workspace]
channels = ["conda-forge", "bioconda"]
name = "funannotate"
platforms = ["linux-64"]
version = "1.8.18"

[tasks]

[activation]
scripts = ["scripts/pixi_setup_symlinks.sh"]

[activation.env]
TRINITY_HOME = "${CONDA_PREFIX}/bin"
EVM_HOME = "${CONDA_PREFIX}/bin"

[dependencies]
blast = ">=2.16.0,<3"
repeatmasker = ">=4.2.3,<5"
repeatmodeler = ">=1.0.8,<2"
miniprot = ">=0.18,<0.19"
minimap2 = ">=2.30,<3"
exonerate = ">=2.4.0,<3"
hmmer = ">=3.4,<4"
python = ">=3.6,<3.9"
biopython = "<1.80"
xlrd = "==1.2.0"
evidencemodeler = "==1.1.1"
pasa = "==2.4.1"
codingquarry = "==2.0"
trinity = ">=2.1.1,<3"
proteinortho = ">=6.3.6,<7"
goatools = ">=1.4.12,<2"
matplotlib-base = ">=3.7.3,<4"
natsort = ">=8.4.0,<9"
numpy = ">=1.24.4,<2"
pigz = ">=2.8,<3"
tantan = ">=51,<52"
bedtools = ">=2.31.1,<3"
diamond = ">=2.0.5"
tbl2asn = ">=25.7,<26"
blat = ">=35,<36"
trnascan-se = ">=2.0"
ucsc-pslcdnafilter = ">=482,<483"
trimmomatic = ">=0.40,<0.41"
fastp = ">=0.23,<1"
raxml = ">=8.2.13,<9"
iqtree = ">=3.1.1,<4"
trimal = ">=1.5.1,<2"
mafft = ">=7"
hisat2 = ">=2.2.2,<3"
kallisto = "==0.46.1"
stringtie = ">=3.0.3,<4"
salmon = ">=0.9"
samtools = ">=1.9"
glimmerhmm = ">=3.0.4,<4"
bamtools = ">=2.5.3,<3"
perl-yaml = ">=1.30,<2"
perl-file-which = ">=1.24,<2"
perl-local-lib = ">=2.29,<3"
perl-dbd-mysql = ">=5.13,<6"
perl-clone = ">=0.46,<0.47"
perl-hash-merge = ">=0.302,<0.303"
perl-soap-lite = ">=1.27,<2"
perl-json = ">=4.11,<5"
perl-logger-simple = ">=2.0,<3"
perl-scalar-util-numeric = ">=0.40,<0.41"
perl-math-utils = ">=1.14,<2"
perl-mce = ">=1.902,<2"
ete3 = ">=3.1.3,<4"
perl-text-soundex = ">=3.5,<4"
perl-parallel-forkmanager = ">=2.4,<3"
perl-db-file = ">=1.855,<2"
distro = ">=1.9.0,<2"
repeatscout = ">=1.0.7,<2"
recon = ">=1.8,<2"
fasta3 = ">=36.3.8,<37"

[pypi-dependencies]
funannotate = { git = "https://github.com/nextgenusfs/funannotate.git", branch="master" }

