Submit-block ::= {
  contact {
    contact {
      name name {
        last "Palmer",
        first "Jonathan",
        middle "",
        initials "",
        suffix "",
        title ""
      },
      affil std {
        affil "USDA Forest Service",
        div "CFMR",
        city "Madison",
        sub "WI",
        country "USA",
        street "1 Gifford Pinchot Drive",
        email "nextgenusfs@gmail.com",
        phone "",
        postal-code "53726"
      }
    }
  },
  cit {
    authors {
      names std {
        {
          name name {
            last "Palmer",
            first "Jonathan",
            middle "",
            initials "M.",
            suffix "",
            title ""
          }
        },
        {
          name name {
            last "Stajich",
            first "Jason",
            middle "",
            initials "E.",
            suffix "",
            title ""
          }
        }
      },
      affil std {
        affil "USDA Forest Service",
        div "CFMR",
        city "Madison",
        sub "WI",
        country "USA",
        street "1 Gifford Pinchot Drive",
        postal-code "53726"
      }
    }
  },
  subtype new
}
Seqdesc ::= pub {
  pub {
    gen {
      cit "unpublished",
      authors {
        names std {
          {
            name name {
              last "Palmer",
              first "Jonathan",
              middle "",
              initials "M.",
              suffix "",
              title ""
            }
          },
          {
            name name {
              last "Stajich",
              first "Jason",
              middle "",
              initials "E.",
              suffix "",
              title ""
            }
          }
        }
      },
      title "Annotate generated by Funannotate: fungal automated genome
 annotation"
    }
  }
}
Seqdesc ::= user {
  type str "DBLink",
  data {
    {
      label str "BioProject",
      num 1,
      data strs {
        "PRJNAXXXXXXXXX"
      }
    },
    {
      label str "BioSample",
      num 1,
      data strs {
        "SAMNXXXXXXXXX"
      }
    }
  }
}
Seqdesc ::= user {
  type str "Submission",
  data {
    {
      label str "AdditionalComment",
      data str "ALT EMAIL:nextgenusfs@gmail.com"
    }
  }
}
Seqdesc ::= user {
  type str "Submission",
  data {
    {
      label str "AdditionalComment",
      data str "Submission Title:None"
    }
  }
}
