Submit-block ::= {
  contact {
    contact {
      name name {
        last "Palmer",
        first "Jonathan"
      },
      affil std {
        affil "USDA Forest Service",
        div "CFMR",
        city "Madison",
        sub "WI",
        country "USA",
        street "1 Gifford Pinchot Drive",
        email "nextgenusfs@gmail.com",
        fax "",
        phone "555-555-5555",
        postal-code "53726"
      }
    }
  },
  cit {
    authors {
      names std {
        {
          name name {
            last "Palmer",
            first "Jonathan",
            initials "J.M.",
            suffix ""
          }
        }
      },
      affil std {
        affil "USDA Forest Service",
        div "CFMR",
        city "Madison",
        sub "WI",
        country "USA",
        street "1 Gifford Pinchot Drive",
        postal-code "53726"
      }
    }
  },
  subtype new
}

Seqdesc ::= pub {
  pub {
    gen {
      cit "unpublished",
      authors {
        names std {
          {
            name name {
              last "Palmer",
              first "Jonathan",
              initials "J.M.",
              suffix ""
            }
          }
        },
        affil std {
          affil "USDA Forest Service",
          div "CFMR",
          city "Madison",
          sub "WI",
          country "USA",
          street "1 Gifford Pinchot Drive",
          postal-code "53726"
        }
      },
      title “Annotate generated by FunAnnotate: fungal automated genome annotation”
    }
  }
}

