# This is a basic workflow to help you get started with Actions

name: Release funannotate-slim to Docker Hub

# Controls when the action will run.
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to publish when manually triggered"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nextgenusfs/funannotate-slim:${{ inputs.release_tag || github.event.release.tag_name }}

      - name: Image digest
        run: echo "digest=${{ steps.docker_build.outputs.digest }}" >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: nextgenusfs/funannotate
          event-type: docker-hub-release-complete
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ inputs.release_tag || github.event.release.tag_name }}"}'
