# This is a basic workflow to help you get started with Actions

name: Release funannotate to Docker Hub

# Controls when the action will run.
on:
  repository_dispatch:
    types: [docker-hub-release-complete]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to publish when manually triggered"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          context: ./
          file: ./Dockerfile2
          push: true
          tags: nextgenusfs/funannotate:${{ inputs.release_tag || github.event.client_payload.tag }}

      - name: Image digest
        run: echo "digest=${{ steps.docker_build.outputs.digest }}" >> $GITHUB_OUTPUT
